export const perguntas = [
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Qual é o domínio de internet do país Tuvalu?",
    correct_answer: ".tv",
    incorrect_answers: [".tu", ".tt", ".tl"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o formato de imagem mais preferido para logos no banco de dados Wikimedia?",
    correct_answer: ".svg",
    incorrect_answers: [".png", ".jpeg", ".gif"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Quantos bits geralmente correspondem a um byte?",
    correct_answer: "8",
    incorrect_answers: ["1", "2", "64"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Quando o Gmail foi lançado pela primeira vez, quanto de armazenamento ele fornecia para seus e-mails?",
    correct_answer: "1GB",
    incorrect_answers: ["512MB", "5GB", "Ilimitado"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Em qualquer linguagem de programação, qual é a maneira mais comum de iterar através de um array?",
    correct_answer: "Loops 'For'",
    incorrect_answers: [
      "Declarações 'If'",
      "Loops 'Do-while'",
      "Loops 'While'",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Qual linguagem é utilizada pelo Node.js?",
    correct_answer: "JavaScript",
    incorrect_answers: ["Java", "Java Source", "Código Fonte Joomla"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Se você codificasse software nesta linguagem, só poderia digitar 0s e 1s.",
    correct_answer: "Binário",
    incorrect_answers: ["JavaScript", "C++", "Python"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o nome do código para o sistema operacional móvel Android 7.0?",
    correct_answer: "Nougat",
    incorrect_answers: ["Ice Cream Sandwich", "Jelly Bean", "Marshmallow"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "De acordo com o Sistema Internacional de Unidades, quantos bytes há em um kilobyte de RAM?",
    correct_answer: "1000",
    incorrect_answers: ["512", "1024", "500"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual dispositivo de hardware de computador fornece uma interface para todos os outros dispositivos conectados se comunicarem?",
    correct_answer: "Placa-mãe",
    incorrect_answers: [
      "Unidade Central de Processamento",
      "Disco Rígido",
      "Memória de Acesso Aleatório",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "A linguagem de programação 'Swift' foi criada para substituir qual outra linguagem de programação?",
    correct_answer: "Objective-C",
    incorrect_answers: ["C#", "Ruby", "C++"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "O que significa CPU?",
    correct_answer: "Unidade Central de Processamento",
    incorrect_answers: [
      "Unidade de Processo Central",
      "Unidade Pessoal de Computador",
      "Unidade de Processador Central",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "O que significa GHz?",
    correct_answer: "Gigahertz",
    incorrect_answers: ["Gigahotz", "Gigahetz", "Gigahatz"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Com qual linguagem de computador você associaria o framework Django?",
    correct_answer: "Python",
    incorrect_answers: ["C#", "C++", "Java"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Em design de web, o que significa CSS?",
    correct_answer: "Folha de Estilo em Cascata",
    incorrect_answers: [
      "Counter Strike: Source",
      "Folha de Estilo Corretiva",
      "Folha de Estilo de Computador",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "HTML é que tipo de linguagem?",
    correct_answer: "Linguagem de Marcação",
    incorrect_answers: [
      "Linguagem de Macro",
      "Linguagem de Programação",
      "Linguagem de Script",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "O que significa LTS no mercado de software?",
    correct_answer: "Suporte de Longo Prazo",
    incorrect_answers: [
      "Serviço de Taco Longo",
      "Velocidade de Transferência Absurda",
      "Velocidade de Turbo Absurda",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Quantos kilobytes há em um gigabyte (em decimal)?",
    correct_answer: "1000000",
    incorrect_answers: ["1024", "1000", "1048576"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "A série de geração de gráficos Intel HD que sucedeu a série 5000 e 6000 (Broadwell) é chamada:",
    correct_answer: "HD Graphics 500",
    incorrect_answers: [
      "HD Graphics 700",
      "HD Graphics 600",
      "HD Graphics 7000",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual empresa foi fundada em 1º de abril de 1976 por Steve Jobs, Steve Wozniak e Ronald Wayne?",
    correct_answer: "Apple",
    incorrect_answers: ["Microsoft", "Atari", "Commodore"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Em computação, o que significa LAN?",
    correct_answer: "Rede de Área Local",
    incorrect_answers: [
      "Nó de Antena Longa",
      "Nó de Acesso Leve",
      "Navegação por Endereço de Terra",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Em 'Hexadecimal', qual cor seria exibida pelo código de cor '#00FF00'?",
    correct_answer: "Verde",
    incorrect_answers: ["Vermelho", "Azul", "Amarelo"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "No Twitter, qual era o limite original de caracteres para um Tweet?",
    correct_answer: "140",
    incorrect_answers: ["120", "160", "100"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "O sistema de numeração com base 16 é mais comumente referido como",
    correct_answer: "Hexadecimal",
    incorrect_answers: ["Binário", "Duodecimal", "Octal"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Quantos valores são possíveis com um único byte?",
    correct_answer: "256",
    incorrect_answers: ["8", "1", "1024"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Qual empresa desenvolveu o sistema operacional Windows?",
    correct_answer: "Microsoft",
    incorrect_answers: ["Apple", "Google", "IBM"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Qual é o principal navegador da web desenvolvido pelo Google?",
    correct_answer: "Chrome",
    incorrect_answers: ["Firefox", "Safari", "Edge"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Qual foi o primeiro computador pessoal produzido pela IBM?",
    correct_answer: "IBM PC 5150",
    incorrect_answers: ["IBM ThinkPad", "IBM Aptiva", "IBM System/360"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual linguagem de programação é conhecida por sua simplicidade e legibilidade?",
    correct_answer: "Python",
    incorrect_answers: ["Assembly", "C++", "Fortran"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Qual dos seguintes é um tipo de software antivírus?",
    correct_answer: "Norton",
    incorrect_answers: ["Photoshop", "WordPress", "AutoCAD"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o nome do algoritmo de criptografia de chave pública desenvolvido por Whitfield Diffie e Martin Hellman?",
    correct_answer: "Algoritmo de Diffie-Hellman",
    incorrect_answers: ["RSA", "AES", "SHA-256"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o código de erro HTTP que indica que uma página não foi encontrada?",
    correct_answer: "404",
    incorrect_answers: ["500", "403", "200"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Qual linguagem de marcação é usada para criar páginas web?",
    correct_answer: "HTML",
    incorrect_answers: ["CSS", "JavaScript", "PHP"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o nome do modelo de rede que segue o conceito de 'cliente-servidor'?",
    correct_answer: "Modelo OSI",
    incorrect_answers: ["Modelo TCP/IP", "Modelo HTTP", "Modelo Ethernet"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é a unidade de medida de largura de banda em redes de computadores?",
    correct_answer: "Mbps",
    incorrect_answers: ["Hz", "V", "Ohm"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Qual sistema operacional móvel é desenvolvido pela Apple?",
    correct_answer: "iOS",
    incorrect_answers: ["Android", "Windows Phone", "Symbian"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Qual é a função principal de um firewall em uma rede?",
    correct_answer: "Segurança",
    incorrect_answers: ["Backup", "Armazenamento", "Navegação"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o nome do sistema de gerenciamento de banco de dados open source mais popular?",
    correct_answer: "MySQL",
    incorrect_answers: ["PostgreSQL", "Oracle", "SQLite"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o principal objetivo da função de hashing em segurança de dados?",
    correct_answer: "Integridade",
    incorrect_answers: ["Confidencialidade", "Autenticação", "Disponibilidade"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é a principal linguagem de programação usada para desenvolvimento Android?",
    correct_answer: "Java",
    incorrect_answers: ["Swift", "Kotlin", "Objective-C"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "O que significa a sigla API em desenvolvimento de software?",
    correct_answer: "Interface de Programação de Aplicações",
    incorrect_answers: [
      "Interface de Processamento de Aplicações",
      "Aplicação de Programação de Interface",
      "Aplicação de Programação de Interface",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o nome do arquivo de configuração utilizado para o gerenciamento de projetos em Node.js?",
    correct_answer: "package.json",
    incorrect_answers: ["config.json", "project.json", "settings.json"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o sistema de gerenciamento de banco de dados usado para a criação de índices e pesquisas eficientes?",
    correct_answer: "SQL",
    incorrect_answers: ["NoSQL", "XML", "JSON"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Qual protocolo é usado para enviar emails na internet?",
    correct_answer: "SMTP",
    incorrect_answers: ["POP3", "IMAP", "HTTP"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual ferramenta é comumente usada para controle de versão de código-fonte?",
    correct_answer: "Git",
    incorrect_answers: ["Subversion", "Mercurial", "Perforce"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o nome do protocolo usado para transferência de arquivos na web?",
    correct_answer: "FTP",
    incorrect_answers: ["HTTP", "SMTP", "POP3"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o nome do algoritmo de compressão de imagens sem perdas desenvolvido pela IBM?",
    correct_answer: "GIF",
    incorrect_answers: ["JPEG", "PNG", "BMP"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o sistema de arquivos usado pelos sistemas operacionais macOS?",
    correct_answer: "APFS",
    incorrect_answers: ["NTFS", "FAT32", "EXT4"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Qual é o nome do sistema de gerenciamento de containers desenvolvido pela Google?",
    correct_answer: "Kubernetes",
    incorrect_answers: ["Docker", "OpenShift", "Mesos"],
  },
];
